name: main_practice
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.19.0
  watcher: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/background.jpg

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/l10n/generated


scripts: dart run merge_and_generate.dart
