// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G-k4VbdZWw-sOEgYgbdSqvXP_59rzwc',
    appId: '1:848096892270:web:d6c351198ba4370606dd7f',
    messagingSenderId: '848096892270',
    projectId: 'biuse-d41d8',
    authDomain: 'biuse-d41d8.firebaseapp.com',
    storageBucket: 'biuse-d41d8.appspot.com',
    measurementId: 'G-QVH8LHH158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrIkYWSf2leUsQV1D0gP0JMQWzz_juQg',
    appId: '1:848096892270:android:5107f5d53977720c06dd7f',
    messagingSenderId: '848096892270',
    projectId: 'biuse-d41d8',
    storageBucket: 'biuse-d41d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-FVQm1Sgs29zOxLUEmOyh7Z-xX0smbQ',
    appId: '1:848096892270:ios:d9943d036126529c06dd7f',
    messagingSenderId: '848096892270',
    projectId: 'biuse-d41d8',
    storageBucket: 'biuse-d41d8.appspot.com',
    iosBundleId: 'com.example.mainPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-FVQm1Sgs29zOxLUEmOyh7Z-xX0smbQ',
    appId: '1:848096892270:ios:d9943d036126529c06dd7f',
    messagingSenderId: '848096892270',
    projectId: 'biuse-d41d8',
    storageBucket: 'biuse-d41d8.appspot.com',
    iosBundleId: 'com.example.mainPractice',
  );
}
